name: "Python Tooling CI"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # 🛡️ Security
  scan:
    uses: BT-IT-Infrastructure-CloudOps/aws-workflows/.github/workflows/reusable-secret-scan.yaml@main

  # 🐍 Python Tests
  test:
    needs: [scan]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Set up Python
        uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.0.0
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install .[test] # Uses pyproject.toml extras

      - name: Run Tests
        run: pytest

      - name: Lint
        run: |
          pip install ruff black
          ruff check .
          black --check .
